apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: outline # Change to your namespace
type: Opaque
data:
  # Base64 encode your MinIO credentials
  access-key: bWluaW8tYWNjZXNzLWtleQ== # "minio-access-key" base64 encoded
  secret-key: bWluaW8tc2VjcmV0LWtleQ== # "minio-secret-key" base64 encoded

---
# Example of how to create the MinIO secret using kubectl:
# kubectl create secret generic minio-credentials \
#   --from-literal=access-key="$(openssl rand -base64 20)" \
#   --from-literal=secret-key="$(openssl rand -base64 32)" \
#   --namespace=outline

---
# Example values.yaml configuration to use this secret:
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-secret-example
data:
  values.yaml: |
    minio:
      enabled: true
      existingSecret: "minio-credentials"
      existingSecretAccessKeyKey: "access-key"
      existingSecretSecretKeyKey: "secret-key"
      # Remove or comment out the hardcoded credentials:
      # secretKey:
      #   password: ""
      # accessKey:
      #   password: ""