apiVersion: v1
kind: Secret
metadata:
  name: outline-secrets
  namespace: outline # Change to your namespace
type: Opaque
data:
  # Generate SECRET_KEY with: openssl rand -hex 32 | base64 -w 0
  SECRET_KEY: NTk3NGUzNmY4MjA4NWYwNTcyMjM1NjVhYzJkMGQwMTQyN2E5MDI0OGFkZTYxMTEwOGI0YjkzNzY3MjY0OWJkNA==

  # Generate UTILS_SECRET with: openssl rand -hex 32 | base64 -w 0
  UTILS_SECRET: OGM1YTE0OTczMzI1YmE1NjY5NGE5OTg1NmU2YmUzMzA4MTJiODc1ZTVmNjgzZGQzNzAyMmNmNzY0NDQ3NzRiYg==

  # Authentication providers (at least one required) - Base64 encode your OAuth secrets
  SLACK_CLIENT_SECRET: eW91ci1zbGFjay1jbGllbnQtc2VjcmV0
  GOOGLE_CLIENT_SECRET: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==
  AZURE_CLIENT_SECRET: eW91ci1henVyZS1jbGllbnQtc2VjcmV0
  DISCORD_CLIENT_SECRET: eW91ci1kaXNjb3JkLWNsaWVudC1zZWNyZXQ=
  OIDC_CLIENT_SECRET: eW91ci1vaWRjLWNsaWVudC1zZWNyZXQ=

  # Email secret
  SMTP_PASSWORD: eW91ci1zbXRwLXBhc3N3b3Jk

  # Integration secrets (optional) - Base64 encode your integration secrets
  GITHUB_CLIENT_SECRET: eW91ci1naXRodWItY2xpZW50LXNlY3JldA==
  GITHUB_WEBHOOK_SECRET: eW91ci1naXRodWItd2ViaG9vay1zZWNyZXQ=
  GITHUB_APP_PRIVATE_KEY: eW91ci1naXRodWItYXBwLXByaXZhdGUta2V5
  LINEAR_CLIENT_SECRET: eW91ci1saW5lYXItY2xpZW50LXNlY3JldA==
  NOTION_CLIENT_SECRET: eW91ci1ub3Rpb24tY2xpZW50LXNlY3JldA==
  SLACK_VERIFICATION_TOKEN: eW91ci1zbGFjay12ZXJpZmljYXRpb24tdG9rZW4=

---
# Example of how to create the secret using kubectl:
# kubectl create secret generic outline-secrets \
#   --from-literal=SECRET_KEY="$(openssl rand -hex 32)" \
#   --from-literal=UTILS_SECRET="$(openssl rand -hex 32)" \
#   --from-literal=SLACK_CLIENT_SECRET="your-slack-client-secret" \
#   --from-literal=GOOGLE_CLIENT_SECRET="your-google-client-secret" \
#   --from-literal=AZURE_CLIENT_SECRET="your-azure-client-secret" \
#   --from-literal=DISCORD_CLIENT_SECRET="your-discord-client-secret" \
#   --from-literal=OIDC_CLIENT_SECRET="your-oidc-client-secret" \
#   --from-literal=SMTP_PASSWORD="your-smtp-password" \
#   --from-literal=GITHUB_CLIENT_SECRET="your-github-client-secret" \
#   --from-literal=GITHUB_WEBHOOK_SECRET="your-github-webhook-secret" \
#   --from-literal=GITHUB_APP_PRIVATE_KEY="your-github-app-private-key" \
#   --from-literal=LINEAR_CLIENT_SECRET="your-linear-client-secret" \
#   --from-literal=NOTION_CLIENT_SECRET="your-notion-client-secret" \
#   --from-literal=SLACK_VERIFICATION_TOKEN="your-slack-verification-token" \
#   --namespace=outline