apiVersion: v1
name: outline
description: The outline helm chart to deploy outline in kubernetes clusters.
version: 0.0.9
appVersion: 0.69.1
home: https://github.com/denkhaus/outline-helm
sources:
  - https://github.com/denkhaus/outline-helm
keywords:
  - outline
  - wiki
  - helm
  - chart
  - kubernetes
  - s3
  - minio
  - postgresql
  - mongodb
  - knowledge
maintainers:
  - name: denkhaus
    url: https://github.com/denkhaus
