apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            # Core application settings
            {{- include "outline.coreEnv" . | nindent 12 }}
            
            # Core secret keys (from Kubernetes secret)
            {{- include "outline.coreSecretEnv" . | nindent 12 }}
            
            # Database configuration
            {{- include "outline.databaseEnv" . | nindent 12 }}
            
            # Redis configuration
            {{- include "outline.redisEnv" . | nindent 12 }}
            
            # S3/Minio configuration
            {{- include "outline.s3Env" . | nindent 12 }}
            
            # Additional environment variables
            {{- include "outline.additionalEnv" . | nindent 12 }}
            
            # Required secret environment variables
            {{- include "outline.requiredSecretEnv" . | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: web
  selector:
    app: {{ .Values.name }}

{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.name }}-tls
  {{ end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  name: web
{{- end }}
