name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz
          tar -xzf chart-releaser_1.6.1_linux_amd64.tar.gz
          sudo mv cr /usr/local/bin/cr

      - name: Package and release charts
        run: |
          # Create packages directory
          mkdir -p .cr-release-packages
          
          # Package charts
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart" --destination .cr-release-packages
            fi
          done
          
          # Upload chart packages to GitHub releases
          cr upload -o denkhaus -r outline-helm -c $(git rev-parse HEAD) --skip-existing
          
          # Update index and push to gh-pages
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          cr index -o denkhaus -r outline-helm -c https://denkhaus.github.io/outline-helm --push
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
